<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFrameworks>net11.0;netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Hopac.FSharpPlus.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharpPlus" Version="1.9.1" />
    <PackageReference Include="Hopac" Version="0.5.1" />
  </ItemGroup>

</Project>
